name = "typography"
license = "Apache-2.0"
licenselink = "https://github.com/danielroelfs/hugo-theme-typography/blob/main/LICENSE"
description = "A simple Hugo theme focused on typography and readability"
homepage = "https://github.com/danielroelfs/hugo-theme-typography"
tags = ["clean", "simple", "minimalist", "typography", ]
features = ["readability", "simple"]
min_version = "0.115.4"

[author]
  name = "Daniel Roelfs"
  homepage = "https://danielroelfs.com"
