name: Test build

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**' 
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HUGO_VERSION: 0.116.1

    steps:
      - name: 🛎 Check out repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm i -g postcss postcss-cli autoprefixer
      - name: 🤵 Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: 🍳 Build site
        run: |
          cd exampleSite
          hugo --themesDir ../.. -d ../docs/ --logLevel info -b https://danielroelfs.github.io/hugo-theme-typography
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
